prepare:
      test_size: 0.33
      random_state: 42
train:
  params:
    random_state: 42
    batch_size: 2048
    epochs: 2
  model_filename: models/model.pkl
evaluate:
  scores_file: metrics/scores.json
  plots_file: metrics/cm_classes.csv
